version: 2
jobs:
  build:
    docker:
      - image: zondax/circleci:latest
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      # Unfortunately need to disable leak sanitizer https://github.com/google/sanitizers/issues/916
      # Still run all other ASAN components
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_only_rust:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - run:
          name: rustfmt
          command: |
            cd ~/project/app/rust
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            cd ~/project/app/rust
            cargo clippy --version
            cargo clippy --all-features --all-targets || true
      - run:
          name: audit
          command: |
            cd ~/project/app/rust
            cargo audit --version
            cargo audit
      - run:
          name: run tests
          command: |
            cd ~/project/app/rust
            cargo test

  build_ledger:
    docker:
      - image: zondax/builder-bolos:latest
    working_directory: ~/project
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      # Docker entrypoint is not considered
      - run: git submodule update --init --recursive
      - run:
          name: Build Standard light parser app
          command: |
            source /home/zondax/.cargo/env
            make SUBSTRATE_PARSER_FULL=0
      - run:
          name: Build Standard full parser app
          command: |
            source /home/zondax/.cargo/env
            make SUBSTRATE_PARSER_FULL=1
      - run:
          name: Build SR25519 app
          command: |
            source /home/zondax/.cargo/env
            make SUPPORT_SR25519=1

  test_zemu:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install rust
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake binutils-dev libcurl4-openssl-dev libiberty-dev libelf-dev libdw-dev
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
          no_output_timeout: 1800s
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.4.0
            nvm use 14.4.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make clean_build && SUBSTRATE_PARSER_FULL=1 make buildS
            make clean_build && SUBSTRATE_PARSER_FULL=1 make buildX
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.4.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.4.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_test

  test_zemu_sr25519:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: Install rust
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake binutils-dev libcurl4-openssl-dev libiberty-dev libelf-dev libdw-dev
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
          no_output_timeout: 1800s
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.4.0
            nvm use 14.4.0
            npm install -g yarn
      - run:
          name: Build Ledger app
          command: |
            make clean_build && SUBSTRATE_PARSER_FULL=1 SUPPORT_SR25519=1 make buildS
      - run:
          name: Build/Install build js deps
          command: |
            nvm use 14.4.0
            export PATH=~/.cargo/bin:$PATH
            make zemu_install
      - run:
          name: Run zemu tests for sr25519
          command: |
            nvm use 14.4.0
            export PATH=~/.cargo/bin:$PATH
            cd tests_zemu && yarn testSR25519

  build_package:
    docker:
      - image: zondax/builder-bolos:latest
    environment:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Build
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make SUBSTRATE_PARSER_FULL=0
      - run: /home/zondax/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(/home/zondax/project/app/pkg/installer_s.sh version) /home/zondax/project/app/pkg/installer_s.sh
      - run:
          name: Clear and rebuild XL version
          command: |
            source /home/zondax/.cargo/env
            cd /home/zondax/project
            make SUBSTRATE_PARSER_FULL=1
      - run: /home/zondax/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(/home/zondax/project/app/pkg/installer_s.sh version) /home/zondax/project/app/pkg/installer_XL_s.sh

workflows:
  version: 2

  default:
    jobs:
      - build
      - build_only_rust
      - build_ledger
      - test_zemu
      - test_zemu_sr25519
      - build_package:
          requires:
            - build
            - build_ledger
            - test_zemu
            - test_zemu_sr25519
          filters:
            branches:
              only:
                - master
